In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2]
a

[1.0, 2.0, 1.0]

In [4]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[0, 1]

tensor(1.)

In [16]:
points[0]

tensor([4., 1.])

In [17]:
some_list = list(range(6))

In [18]:
some_list

[0, 1, 2, 3, 4, 5]

In [19]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [20]:
some_list[1:4]

[1, 2, 3]

In [21]:
some_list[1:-1:2]

[1, 3]

In [22]:
some_list[:4]

[0, 1, 2, 3]

In [23]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])
weights_named

/var/folders/3r/k180sfj978x4123l_663qc100000gn/T/ipykernel_51178/2163324119.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /Users/distiller/project/pytorch/c10/core/TensorImpl.h:1463.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [24]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [25]:
img_t

tensor([[[-1.2327e+00, -2.3344e-02, -6.5754e-01, -1.7094e+00, -3.0275e+00],
         [ 2.1817e+00, -1.1256e+00,  1.2317e+00, -4.5001e-01,  5.4928e-01],
         [-5.0549e-01,  1.0682e-01, -1.2941e+00,  1.0288e+00, -2.0825e+00],
         [ 5.4010e-01,  8.7953e-01, -2.0270e+00,  7.0659e-01,  2.5648e+00],
         [ 1.1922e+00,  1.9413e+00, -1.1000e+00,  1.0984e+00,  9.4957e-01]],

        [[ 9.3871e-01,  1.9045e+00, -1.7839e-03, -5.4998e-01,  5.6933e-01],
         [-7.8183e-01, -1.2787e+00,  1.1414e+00, -9.0239e-01,  3.4446e-01],
         [ 1.5634e+00, -1.4023e+00, -1.1125e+00,  6.7771e-01,  7.6736e-01],
         [ 1.1682e+00,  4.0873e-01,  1.7525e-01,  9.8764e-01,  3.6195e-01],
         [-6.3165e-01, -3.6213e-01, -8.1117e-01,  1.3795e-01,  1.1528e+00]],

        [[-1.1421e+00, -4.4311e-01,  6.0138e-02,  1.6861e+00,  2.2220e-01],
         [ 8.3536e-01, -2.4721e-01, -7.6622e-01,  6.3806e-01,  2.8340e-01],
         [-1.0375e+00,  1.0830e+00, -5.3195e-01, -9.7182e-01,  7.5787e-01],
        

In [26]:
batch_t = torch.randn(2, 3, 5, 5)

In [27]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [28]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [29]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [31]:
img_gray_weighted_fancy = torch.einsum('...chw, c->...hw',img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw, c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [32]:
img_gray_weighted_fancy.shape

torch.Size([5, 5])

In [35]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [36]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')
